notifications:
  email:
    on_success: always
script: 'bundle exec rake'
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
#  - rbx # Removed because travis is choking on rbx and doesn't find rbx-2.0.0-rc1 which was tested locally 
  - jruby-18mode
  - jruby-19mode
